replicaCount: 1
clusterName: mstartr-aks
pathBase: /webstatus

image:
  repository: manvekar/msstrwebstatus
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {

  }
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: HealthChecks-UI__HealthChecks__0__Name
      key: name__mvc__hc
    - name: HealthChecks-UI__HealthChecks__0__Uri
      key: internalurls__mvc__hc
    - name: HealthChecks-UI__HealthChecks__1__Name
      key: name__identity__hc
    - name: HealthChecks-UI__HealthChecks__1__Uri
      key: internalurls__identity__hc

      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
