version: '3.4'

services:

 sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

 identity-api:
    image: ${REGISTRY:-msstr}/msstridentity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
       context: .
       dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
       - sqldata
 
 webmvc:
    image: ${REGISTRY:-msstr}/msstrwebmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile

