version: '3.4'

services:

 sqldata:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6433:5432"
    volumes:
      - msstr-sqldata:/var/lib/postgres  

 identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${MSSTR_AZURE_IDENTITY_DB:-Host=host.docker.internal;Port=6433;Database=microServiceStarter.Service.IdentityDb;Username=postgres;Password=postgres}
      - MvcClient=http://${MSSTR_EXTERNAL_DNS_NAME_OR_IP}:6100
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
    - "6105:80"

 webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://${MSSTR_EXTERNAL_DNS_NAME_OR_IP}:6105
      - IdentityUrlHC=http://identity-api/hc
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "6100:80"
volumes:
  msstr-sqldata:
    external: false
