version: '3.4'

services:

 sqldata:
    image: postgres:latest

 identity-api:
    image: ${REGISTRY:-manvekar}/msstridentity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
       context: .
       dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
       - sqldata
 
 webmvc:
    image: ${REGISTRY:-manvekar}/msstrwebmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile

 webstatus:
    image: ${REGISTRY:-manvekar}/msstrwebstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile
